// Comprehensive Job Listings Data
const jobsData = [
            {
                id: 4001,
                title: "Data Analyst",
                company: "Insight Analytics",
                location: "Lahore, Pakistan",
                type: "full-time",
                category: "technology",
                salary: "Rs. 120,000 - Rs. 170,000",
                logo: "IA",
                description: "Analyze data sets to provide actionable insights for business decisions. Work with SQL, Python, and BI tools.",
                tags: ["Data Analysis", "SQL", "Python", "BI", "Reporting"],
                posted: "Today",
                remote: false
            },
            {
                id: 4002,
                title: "HR Manager",
                company: "TalentPro",
                location: "Karachi, Pakistan",
                type: "full-time",
                category: "management",
                salary: "Rs. 130,000 - Rs. 180,000",
                logo: "TP",
                description: "Lead HR operations, recruitment, and employee engagement. Develop policies and manage talent acquisition.",
                tags: ["HR", "Recruitment", "Employee Relations", "Policy", "Talent Acquisition"],
                posted: "Today",
                remote: false
            },
            {
                id: 4003,
                title: "Web Developer",
                company: "WebWorks",
                location: "Islamabad, Pakistan",
                type: "full-time",
                category: "technology",
                salary: "Rs. 110,000 - Rs. 160,000",
                logo: "WW",
                description: "Develop and maintain websites using HTML, CSS, JavaScript, and PHP. Collaborate with designers and backend teams.",
                tags: ["HTML", "CSS", "JavaScript", "PHP", "Web Development"],
                posted: "Today",
                remote: false
            },
            {
                id: 4004,
                title: "Open Stack Developer",
                company: "CloudStack",
                location: "Lahore, Pakistan",
                type: "full-time",
                category: "technology",
                salary: "Rs. 150,000 - Rs. 200,000",
                logo: "CS",
                description: "Build and manage OpenStack cloud solutions. Integrate with DevOps and automation tools.",
                tags: ["OpenStack", "Cloud", "DevOps", "Python", "Automation"],
                posted: "Today",
                remote: false
            },
            {
                id: 4005,
                title: "Network Engineer",
                company: "NetPro",
                location: "Karachi, Pakistan",
                type: "full-time",
                category: "technology",
                salary: "Rs. 130,000 - Rs. 180,000",
                logo: "NP",
                description: "Design, implement, and manage network infrastructure. Troubleshoot and optimize performance.",
                tags: ["Networking", "Cisco", "Firewall", "LAN", "WAN"],
                posted: "Today",
                remote: false
            },
            {
                id: 4006,
                title: "Business Intelligence Analyst",
                company: "BI Solutions",
                location: "Islamabad, Pakistan",
                type: "full-time",
                category: "technology",
                salary: "Rs. 140,000 - Rs. 190,000",
                logo: "BI",
                description: "Develop BI dashboards and reports. Analyze business data to support decision-making.",
                tags: ["BI", "Power BI", "Tableau", "SQL", "Reporting"],
                posted: "Today",
                remote: false
            },
            {
                id: 4007,
                title: "Mobile Application Developer",
                company: "AppGen",
                location: "Lahore, Pakistan",
                type: "full-time",
                category: "technology",
                salary: "Rs. 120,000 - Rs. 170,000",
                logo: "AG",
                description: "Develop mobile apps for Android and iOS platforms. Work with cross-functional teams.",
                tags: ["Android", "iOS", "Flutter", "React Native", "Mobile Development"],
                posted: "Today",
                remote: false
            },
            {
                id: 4008,
                title: "Cloud Solutions Architect",
                company: "CloudPro",
                location: "Karachi, Pakistan",
                type: "full-time",
                category: "technology",
                salary: "Rs. 180,000 - Rs. 250,000",
                logo: "CP",
                description: "Design and implement cloud solutions for enterprise clients. Lead migration and modernization projects.",
                tags: ["Cloud", "AWS", "Azure", "Architecture", "Migration"],
                posted: "Today",
                remote: false
            },
            {
                id: 4009,
                title: "QA Automation Engineer",
                company: "TestPro",
                location: "Islamabad, Pakistan",
                type: "full-time",
                category: "technology",
                salary: "Rs. 110,000 - Rs. 150,000",
                logo: "TP",
                description: "Automate testing for web and mobile applications. Ensure product quality and reliability.",
                tags: ["QA", "Automation", "Selenium", "Testing", "CI/CD"],
                posted: "Today",
                remote: false
            },
            {
                id: 4010,
                title: "Frontend Engineer",
                company: "PixelEdge",
                location: "Lahore, Pakistan",
                type: "full-time",
                category: "technology",
                salary: "Rs. 120,000 - Rs. 170,000",
                logo: "PE",
                description: "Build modern web interfaces using React and Vue. Optimize performance and user experience.",
                tags: ["React", "Vue", "JavaScript", "HTML", "CSS"],
                posted: "Today",
                remote: false
            },
        // Placeholder jobs for empty categories
        {
            id: 3001,
            title: "Communication Specialist",
            company: "ConnectPro Ltd",
            location: "Lahore, Pakistan",
            type: "full-time",
            category: "communication",
            salary: "Rs. 110,000 - Rs. 150,000",
            logo: "CP",
            description: "Develop and execute internal and external communication strategies. Foster effective messaging across the organization.",
            tags: ["Communication", "Strategy", "Public Relations", "Writing"],
            posted: "Today",
            remote: false
        },
        {
            id: 3002,
            title: "Teamwork Coordinator",
            company: "Synergy Solutions",
            location: "Karachi, Pakistan",
            type: "full-time",
            category: "teamwork",
            salary: "Rs. 120,000 - Rs. 160,000",
            logo: "SS",
            description: "Lead cross-functional teams to achieve project goals. Promote a collaborative and inclusive work environment.",
            tags: ["Teamwork", "Collaboration", "Leadership", "Project Management"],
            posted: "Today",
            remote: false
        },
        {
            id: 3003,
            title: "Leadership Trainer",
            company: "LeadEdge Group",
            location: "Islamabad, Pakistan",
            type: "full-time",
            category: "leadership",
            salary: "Rs. 140,000 - Rs. 180,000",
            logo: "LE",
            description: "Design and deliver leadership training programs. Coach managers and executives to enhance their leadership skills.",
            tags: ["Leadership", "Coaching", "Training", "HR"],
            posted: "Today",
            remote: false
        },
        {
            id: 3004,
            title: "Problem-Solving Analyst",
            company: "SolutionWorks",
            location: "Lahore, Pakistan",
            type: "full-time",
            category: "problem-solving",
            salary: "Rs. 115,000 - Rs. 155,000",
            logo: "SW",
            description: "Analyze business challenges and develop actionable solutions. Facilitate problem-solving workshops.",
            tags: ["Problem Solving", "Analysis", "Facilitation", "Consulting"],
            posted: "Today",
            remote: false
        },
        {
            id: 3005,
            title: "Critical Thinking Consultant",
            company: "ThinkSmart Consulting",
            location: "Karachi, Pakistan",
            type: "full-time",
            category: "critical-thinking",
            salary: "Rs. 125,000 - Rs. 165,000",
            logo: "TS",
            description: "Guide teams in applying critical thinking to business decisions. Develop frameworks for logical analysis.",
            tags: ["Critical Thinking", "Analysis", "Strategy", "Consulting"],
            posted: "Today",
            remote: false
        },
        {
            id: 3006,
            title: "Creativity Director",
            company: "Imagination Studio",
            location: "Islamabad, Pakistan",
            type: "full-time",
            category: "creativity",
            salary: "Rs. 150,000 - Rs. 200,000",
            logo: "IS",
            description: "Lead creative projects and campaigns. Inspire innovation and originality in design and content.",
            tags: ["Creativity", "Design", "Innovation", "Art Direction"],
            posted: "Today",
            remote: false
        },
        {
            id: 3007,
            title: "Adaptability Coach",
            company: "ChangeMakers",
            location: "Lahore, Pakistan",
            type: "full-time",
            category: "adaptability",
            salary: "Rs. 110,000 - Rs. 145,000",
            logo: "CM",
            description: "Help organizations and individuals adapt to change. Deliver workshops on resilience and flexibility.",
            tags: ["Adaptability", "Coaching", "Change Management", "Training"],
            posted: "Today",
            remote: false
        },
        {
            id: 3008,
            title: "Time Management Consultant",
            company: "EfficientWork",
            location: "Karachi, Pakistan",
            type: "full-time",
            category: "time-management",
            salary: "Rs. 105,000 - Rs. 140,000",
            logo: "EW",
            description: "Advise clients on optimizing productivity and managing time effectively. Develop custom time management plans.",
            tags: ["Time Management", "Productivity", "Consulting", "Training"],
            posted: "Today",
            remote: false
        },
    {
        id: 1,
        title: "Senior Data Analyst",
        company: "TechVision Analytics",
        location: "Lahore, Pakistan",
        type: "full-time",
        category: "technology",
        salary: "Rs. 150,000 - Rs. 200,000",
        logo: "TV",
        description: "We're seeking an experienced Data Analyst to join our growing analytics team. You'll work with large datasets to uncover insights that drive business decisions.",
        tags: ["Python", "SQL", "Tableau", "Machine Learning", "Statistics"],
        posted: "2 days ago",
        remote: false
    },
    {
        id: 2,
        title: "HR Manager",
        company: "Global Enterprises Inc",
        location: "Karachi, Pakistan",
        type: "full-time",
        category: "management",
        salary: "Rs. 120,000 - Rs. 180,000",
        logo: "GE",
        description: "Lead our HR department in talent acquisition, employee relations, and organizational development. Ideal candidate has 5+ years of HR experience.",
        tags: ["Recruitment", "Employee Relations", "HRIS", "Leadership", "Compensation"],
        posted: "1 week ago",
        remote: false
    },
    {
        id: 3,
        title: "Full Stack Software Engineer",
        company: "CloudTech Solutions",
        location: "Islamabad, Pakistan",
        type: "full-time",
        category: "technology",
        salary: "Rs. 180,000 - Rs. 250,000",
        logo: "CT",
        description: "Join our engineering team to build scalable cloud applications. Work with modern technologies and contribute to architectural decisions.",
        tags: ["React", "Node.js", "AWS", "Docker", "TypeScript"],
        posted: "3 days ago",
        remote: false
    },
    {
        id: 4,
        title: "Digital Marketing Manager",
        company: "BrandBoost Marketing",
        location: "Lahore, Pakistan",
        type: "full-time",
        category: "marketing",
        salary: "Rs. 100,000 - Rs. 150,000",
        logo: "BB",
        description: "Drive digital marketing strategies across multiple channels. Manage campaigns, analyze performance, and lead a team of marketing specialists.",
        tags: ["SEO", "SEM", "Social Media", "Analytics", "Content Strategy"],
        posted: "5 days ago",
        remote: false
    },
    {
        id: 5,
        title: "Financial Analyst",
        company: "Capital Finance Group",
        location: "Karachi, Pakistan",
        type: "full-time",
        category: "finance",
        salary: "Rs. 110,000 - Rs. 160,000",
        logo: "CF",
        description: "Analyze financial data, prepare reports, and provide insights to support strategic business decisions. CFA certification preferred.",
        tags: ["Excel", "Financial Modeling", "SAP", "Forecasting", "Reporting"],
        posted: "1 day ago",
        remote: false
    },
    {
        id: 6,
        title: "UX/UI Designer",
        company: "DesignPro Studio",
        location: "Rawalpindi, Pakistan",
        type: "full-time",
        category: "design",
        salary: "Rs. 90,000 - Rs. 140,000",
        logo: "DP",
        description: "Create beautiful, user-centered designs for web and mobile applications. Work closely with product and engineering teams.",
        tags: ["Figma", "Adobe XD", "User Research", "Prototyping", "Design Systems"],
        posted: "4 days ago",
        remote: false
    },
    {
        id: 7,
        title: "Product Manager",
        company: "InnovateTech",
        location: "Islamabad, Pakistan",
        type: "full-time",
        category: "management",
        salary: "Rs. 200,000 - Rs. 280,000",
        logo: "IT",
        description: "Lead product strategy and roadmap for our flagship SaaS platform. Work with cross-functional teams to deliver exceptional products.",
        tags: ["Product Strategy", "Agile", "Roadmapping", "Analytics", "Stakeholder Management"],
        posted: "1 week ago",
        remote: false
    },
    {
        id: 8,
        title: "DevOps Engineer",
        company: "CloudScale Systems",
        location: "Lahore, Pakistan",
        type: "full-time",
        category: "technology",
        salary: "Rs. 170,000 - Rs. 230,000",
        logo: "CS",
        description: "Build and maintain CI/CD pipelines, manage cloud infrastructure, and ensure system reliability and performance.",
        tags: ["Kubernetes", "AWS", "Terraform", "Jenkins", "Python"],
        posted: "2 days ago",
        remote: false
    },
    {
        id: 9,
        title: "Business Development Manager",
        company: "GrowthVentures LLC",
        location: "Faisalabad, Pakistan",
        type: "full-time",
        category: "management",
        salary: "Rs. 130,000 - Rs. 190,000",
        logo: "GV",
        description: "Identify and pursue new business opportunities, build strategic partnerships, and drive revenue growth.",
        tags: ["Sales", "Negotiation", "CRM", "Strategy", "Networking"],
        posted: "3 days ago",
        remote: false
    },
    {
        id: 10,
        title: "Data Scientist",
        company: "AI Innovations Lab",
        location: "Islamabad, Pakistan",
        type: "full-time",
        category: "technology",
        salary: "Rs. 190,000 - Rs. 270,000",
        logo: "AI",
        description: "Apply machine learning and statistical methods to solve complex business problems. Work with cutting-edge AI technologies.",
        tags: ["Python", "TensorFlow", "Deep Learning", "NLP", "R"],
        posted: "1 day ago",
        remote: false
    },
    {
        id: 11,
        title: "Content Marketing Specialist",
        company: "MediaFlow Agency",
        location: "Lahore, Pakistan",
        type: "full-time",
        category: "marketing",
        salary: "Rs. 80,000 - Rs. 120,000",
        logo: "MF",
        description: "Create compelling content across multiple platforms. Develop content strategies that engage audiences and drive conversions.",
        tags: ["Copywriting", "SEO", "Content Strategy", "Social Media", "Analytics"],
        posted: "6 days ago",
        remote: false
    },
    {
        id: 12,
        title: "Cybersecurity Analyst",
        company: "SecureNet Technologies",
        location: "Karachi, Pakistan",
        type: "full-time",
        category: "technology",
        salary: "Rs. 160,000 - Rs. 210,000",
        logo: "SN",
        description: "Protect organizational systems and data from cyber threats. Monitor security systems and respond to incidents.",
        tags: ["Security", "Penetration Testing", "SIEM", "Compliance", "Risk Management"],
        posted: "2 days ago",
        remote: false
    },
    {
        id: 13,
        title: "Registered Nurse - ICU",
        company: "Shifa International Hospital",
        location: "Islamabad, Pakistan",
        type: "full-time",
        category: "healthcare",
        salary: "Rs. 90,000 - Rs. 130,000",
        logo: "SH",
        description: "Provide critical care to ICU patients. Work in a fast-paced environment with state-of-the-art medical equipment.",
        tags: ["Critical Care", "Patient Care", "EMR", "BLS", "ACLS"],
        posted: "1 day ago",
        remote: false
    },
    {
        id: 14,
        title: "Account Executive",
        company: "SalesPro Solutions",
        location: "Lahore, Pakistan",
        type: "full-time",
        category: "management",
        salary: "Rs. 110,000 - Rs. 160,000 + Commission",
        logo: "SP",
        description: "Manage client relationships and drive sales for our B2B software solutions. Excellent earning potential with uncapped commission.",
        tags: ["B2B Sales", "Salesforce", "Account Management", "Negotiation", "Presentation"],
        posted: "4 days ago",
        remote: false
    },
    {
        id: 15,
        title: "Mobile App Developer",
        company: "AppWorks Studio",
        location: "Multan, Pakistan",
        type: "full-time",
        category: "technology",
        salary: "Rs. 140,000 - Rs. 200,000",
        logo: "AW",
        description: "Develop native mobile applications for iOS and Android. Work on apps used by millions of users worldwide.",
        tags: ["React Native", "Swift", "Kotlin", "Firebase", "Mobile UI"],
        posted: "3 days ago",
        remote: false
    },
    {
        id: 16,
        title: "Operations Manager",
        company: "LogisticsPro Inc",
        location: "Karachi, Pakistan",
        type: "full-time",
        category: "management",
        salary: "Rs. 150,000 - Rs. 200,000",
        logo: "LP",
        description: "Oversee daily operations, optimize processes, and manage teams to ensure efficient business operations.",
        tags: ["Operations", "Process Improvement", "Team Management", "Logistics", "Analytics"],
        posted: "5 days ago",
        remote: false
    },
    {
        id: 17,
        title: "Junior Data Analyst",
        company: "StartUp Analytics",
        location: "Peshawar, Pakistan",
        type: "full-time",
        category: "technology",
        salary: "Rs. 60,000 - Rs. 90,000",
        logo: "SA",
        description: "Entry-level position perfect for recent graduates. Learn from experienced data professionals while working on real projects.",
        tags: ["SQL", "Excel", "Python", "Data Visualization", "Statistics"],
        posted: "2 days ago",
        remote: false
    },
    {
        id: 18,
        title: "Senior Accountant",
        company: "Finance Masters LLC",
        location: "Karachi, Pakistan",
        type: "full-time",
        category: "finance",
        salary: "Rs. 120,000 - Rs. 170,000",
        logo: "FM",
        description: "Manage financial reporting, audits, and compliance. ACCA/CA required with 5+ years of accounting experience.",
        tags: ["IFRS", "Financial Reporting", "QuickBooks", "Tax", "Audit"],
        posted: "1 week ago",
        remote: false
    },
    {
        id: 19,
        title: "Machine Learning Engineer",
        company: "DeepTech AI",
        location: "Lahore, Pakistan",
        type: "full-time",
        category: "technology",
        salary: "Rs. 220,000 - Rs. 300,000",
        logo: "DT",
        description: "Design and implement ML models for production systems. Work on cutting-edge AI projects with global impact.",
        tags: ["PyTorch", "MLOps", "Python", "Computer Vision", "NLP"],
        posted: "2 days ago",
        remote: false
    },
    {
        id: 20,
        title: "HR Business Partner",
        company: "PeopleFirst Corp",
        location: "Islamabad, Pakistan",
        type: "full-time",
        category: "management",
        salary: "Rs. 140,000 - Rs. 180,000",
        logo: "PF",
        description: "Partner with business leaders to align HR strategies with business objectives. Focus on talent development and organizational effectiveness.",
        tags: ["HR Strategy", "Talent Management", "Change Management", "Coaching", "Analytics"],
        posted: "4 days ago",
        remote: false
    },
    {
        id: 21,
        title: "Cloud Architect",
        company: "CloudFirst Solutions",
        location: "Islamabad, Pakistan",
        type: "full-time",
        category: "technology",
        salary: "Rs. 250,000 - Rs. 350,000",
        logo: "CF",
        description: "Design scalable cloud architectures for enterprise clients. Lead cloud migration and modernization projects.",
        tags: ["AWS", "Azure", "GCP", "Architecture", "Microservices"],
        posted: "3 days ago",
        remote: false
    },
    {
        id: 22,
        title: "Social Media Manager",
        company: "Viral Marketing Co",
        location: "Lahore, Pakistan",
        type: "full-time",
        category: "marketing",
        salary: "Rs. 90,000 - Rs. 130,000",
        logo: "VM",
        description: "Manage social media presence across platforms, create engaging content, and grow online communities.",
        tags: ["Instagram", "TikTok", "Content Creation", "Analytics", "Community Management"],
        posted: "5 days ago",
        remote: false
    },
    {
        id: 23,
        title: "Quality Assurance Engineer",
        company: "TestPro Systems",
        location: "Rawalpindi, Pakistan",
        type: "full-time",
        category: "technology",
        salary: "Rs. 120,000 - Rs. 170,000",
        logo: "TP",
        description: "Ensure software quality through comprehensive testing strategies. Develop automated test frameworks.",
        tags: ["Selenium", "Test Automation", "Java", "CI/CD", "API Testing"],
        posted: "1 day ago",
        remote: false
    },
    {
        id: 24,
        title: "Investment Analyst",
        company: "Wealth Management Group",
        location: "Karachi, Pakistan",
        type: "full-time",
        category: "finance",
        salary: "Rs. 140,000 - Rs. 200,000",
        logo: "WM",
        description: "Research investment opportunities, analyze market trends, and provide recommendations to portfolio managers.",
        tags: ["Financial Analysis", "Bloomberg", "Excel", "Portfolio Management", "Research"],
        posted: "6 days ago",
        remote: false
    },
    {
        id: 25,
        title: "Project Manager",
        company: "BuildRight Construction",
        location: "Gujranwala, Pakistan",
        type: "full-time",
        category: "management",
        salary: "Rs. 160,000 - Rs. 210,000",
        logo: "BR",
        description: "Manage construction projects from planning to completion. Coordinate teams, budgets, and timelines.",
        tags: ["Project Management", "PMP", "Budgeting", "Scheduling", "Risk Management"],
        posted: "3 days ago",
        remote: false
    },
    {
        id: 26,
        title: "Data Engineer",
        company: "DataFlow Technologies",
        location: "Lahore, Pakistan",
        type: "full-time",
        category: "technology",
        salary: "Rs. 180,000 - Rs. 240,000",
        logo: "DF",
        description: "Build and maintain data pipelines and infrastructure. Work with big data technologies to enable analytics.",
        tags: ["Spark", "Airflow", "SQL", "ETL", "Data Warehousing"],
        posted: "2 days ago",
        remote: false
    },
    {
        id: 27,
        title: "Graphic Designer",
        company: "Creative Studio Plus",
        location: "Sialkot, Pakistan",
        type: "full-time",
        category: "design",
        salary: "Rs. 70,000 - Rs. 110,000",
        logo: "CP",
        description: "Create visual designs for digital and print media. Work on branding, marketing materials, and web graphics.",
        tags: ["Adobe Creative Suite", "Branding", "Typography", "Print Design", "Illustration"],
        posted: "4 days ago",
        remote: false
    },
    {
        id: 28,
        title: "Sales Operations Manager",
        company: "RevOps Solutions",
        location: "Karachi, Pakistan",
        type: "full-time",
        category: "management",
        salary: "Rs. 150,000 - Rs. 200,000",
        logo: "RS",
        description: "Optimize sales processes, manage CRM systems, and provide data-driven insights to sales leadership.",
        tags: ["Salesforce", "Sales Analytics", "Process Optimization", "Automation", "Reporting"],
        posted: "5 days ago",
        remote: false
    },
    {
        id: 29,
        title: "Backend Developer",
        company: "CodeCraft Inc",
        location: "Islamabad, Pakistan",
        type: "full-time",
        category: "technology",
        salary: "Rs. 140,000 - Rs. 190,000",
        logo: "CC",
        description: "Develop robust backend systems and APIs. Work with microservices architecture and modern cloud technologies.",
        tags: ["Java", "Spring Boot", "PostgreSQL", "Redis", "Microservices"],
        posted: "1 day ago",
        remote: false
    },
    {
        id: 30,
        title: "Customer Success Manager",
        company: "ClientFirst SaaS",
        location: "Lahore, Pakistan",
        type: "full-time",
        category: "management",
        salary: "Rs. 120,000 - Rs. 160,000",
        logo: "CF",
        description: "Ensure customer satisfaction and retention. Build strong relationships and drive product adoption.",
        tags: ["Customer Success", "SaaS", "Account Management", "Communication", "Analytics"],
        posted: "3 days ago",
        remote: false
    },
        {
            id: 2001,
            title: "Backend Developer",
            company: "CodeWorks Ltd",
            location: "Lahore, Pakistan",
            type: "full-time",
            category: "technology",
            salary: "Rs. 140,000 - Rs. 190,000",
            logo: "CW",
            description: "Develop robust backend systems and APIs using modern frameworks. Collaborate with frontend and DevOps teams.",
            tags: ["Node.js", "Express", "MongoDB", "REST", "Microservices"],
            posted: "Today",
            remote: false
        },
        {
            id: 2002,
            title: "Frontend Developer",
            company: "PixelSoft",
            location: "Karachi, Pakistan",
            type: "full-time",
            category: "technology",
            salary: "Rs. 120,000 - Rs. 170,000",
            logo: "PS",
            description: "Build responsive web interfaces and user experiences. Work with React, Vue, and modern CSS frameworks.",
            tags: ["React", "Vue", "HTML", "CSS", "JavaScript"],
            posted: "Today",
            remote: false
        },
        {
            id: 2003,
            title: "Full Stack Developer",
            company: "StackFusion",
            location: "Islamabad, Pakistan",
            type: "full-time",
            category: "technology",
            salary: "Rs. 180,000 - Rs. 250,000",
            logo: "SF",
            description: "Work across backend and frontend stacks to deliver complete web solutions. Lead integration and deployment efforts.",
            tags: ["React", "Node.js", "SQL", "AWS", "DevOps"],
            posted: "Today",
            remote: false
        },
        {
            id: 2004,
            title: "HR Manager",
            company: "PeopleMatter",
            location: "Lahore, Pakistan",
            type: "full-time",
            category: "management",
            salary: "Rs. 130,000 - Rs. 180,000",
            logo: "PM",
            description: "Lead HR operations, recruitment, and employee engagement. Develop policies and manage talent acquisition.",
            tags: ["HR", "Recruitment", "Employee Relations", "Policy", "Talent Acquisition"],
            posted: "Today",
            remote: false
        },
        {
            id: 2005,
            title: "DevOps Engineer",
            company: "CloudOps Solutions",
            location: "Karachi, Pakistan",
            type: "full-time",
            category: "technology",
            salary: "Rs. 170,000 - Rs. 220,000",
            logo: "CO",
            description: "Automate deployment pipelines and manage cloud infrastructure. Ensure system reliability and scalability.",
            tags: ["AWS", "Docker", "Kubernetes", "CI/CD", "Terraform"],
            posted: "Today",
            remote: false
        },
        {
            id: 2006,
            title: "UI/UX Designer",
            company: "DesignHub",
            location: "Islamabad, Pakistan",
            type: "full-time",
            category: "design",
            salary: "Rs. 110,000 - Rs. 150,000",
            logo: "DH",
            description: "Design intuitive user interfaces and experiences for web and mobile apps. Conduct user research and prototyping.",
            tags: ["Figma", "Sketch", "User Research", "Wireframes", "Prototyping"],
            posted: "Today",
            remote: false
        },
        {
            id: 2007,
            title: "Project Manager",
            company: "BuildRight",
            location: "Lahore, Pakistan",
            type: "full-time",
            category: "project-management",
            salary: "Rs. 160,000 - Rs. 210,000",
            logo: "BR",
            description: "Manage project timelines, budgets, and teams. Ensure successful delivery of client projects.",
            tags: ["Project Management", "Agile", "Scrum", "Budgeting", "Scheduling"],
            posted: "Today",
            remote: false
        },
        {
            id: 2008,
            title: "Business Analyst",
            company: "InsightPro",
            location: "Karachi, Pakistan",
            type: "full-time",
            category: "management",
            salary: "Rs. 120,000 - Rs. 160,000",
            logo: "IP",
            description: "Analyze business processes and requirements. Bridge communication between stakeholders and development teams.",
            tags: ["Business Analysis", "Requirements", "Documentation", "Stakeholder Management"],
            posted: "Today",
            remote: false
        },
        {
            id: 2009,
            title: "QA Engineer",
            company: "Testify",
            location: "Islamabad, Pakistan",
            type: "full-time",
            category: "technology",
            salary: "Rs. 110,000 - Rs. 150,000",
            logo: "TE",
            description: "Develop and execute test plans for web and mobile applications. Automate testing and ensure product quality.",
            tags: ["Selenium", "Test Automation", "Manual Testing", "API Testing"],
            posted: "Today",
            remote: false
        },
        {
            id: 2010,
            title: "Mobile App Developer",
            company: "AppMakers",
            location: "Lahore, Pakistan",
            type: "full-time",
            category: "technology",
            salary: "Rs. 140,000 - Rs. 200,000",
            logo: "AM",
            description: "Develop native and cross-platform mobile apps. Collaborate with designers and backend teams.",
            tags: ["Flutter", "React Native", "Android", "iOS", "Firebase"],
            posted: "Today",
            remote: false
        },
        {
            id: 2011,
            title: "Digital Marketing Specialist",
            company: "MarketPro",
            location: "Karachi, Pakistan",
            type: "full-time",
            category: "marketing",
            salary: "Rs. 100,000 - Rs. 140,000",
            logo: "MP",
            description: "Plan and execute digital marketing campaigns. Analyze performance and optimize strategies.",
            tags: ["SEO", "SEM", "Social Media", "Analytics", "Content Marketing"],
            posted: "Today",
            remote: false
        },
        {
            id: 2012,
            title: "Sales Executive",
            company: "SalesForce Pakistan",
            location: "Islamabad, Pakistan",
            type: "full-time",
            category: "sales",
            salary: "Rs. 100,000 - Rs. 140,000 + Commission",
            logo: "SF",
            description: "Drive sales growth and manage client accounts. Achieve targets and build lasting relationships.",
            tags: ["Sales", "Account Management", "Negotiation", "CRM"],
            posted: "Today",
            remote: false
        },
        {
            id: 2013,
            title: "Customer Service Representative",
            company: "ServiceFirst",
            location: "Lahore, Pakistan",
            type: "full-time",
            category: "customer-service",
            salary: "Rs. 80,000 - Rs. 110,000",
            logo: "SF",
            description: "Provide excellent customer support and resolve queries. Maintain high satisfaction levels.",
            tags: ["Customer Service", "Support", "CRM", "Communication"],
            posted: "Today",
            remote: false
        },
        {
            id: 2014,
            title: "Content Writer",
            company: "WriteRight",
            location: "Karachi, Pakistan",
            type: "full-time",
            category: "writing",
            salary: "Rs. 90,000 - Rs. 120,000",
            logo: "WR",
            description: "Create engaging content for blogs, websites, and social media. Edit and proofread articles.",
            tags: ["Writing", "Editing", "SEO", "Content Creation"],
            posted: "Today",
            remote: false
        },
        {
            id: 2015,
            title: "Research Scientist",
            company: "LabTech",
            location: "Islamabad, Pakistan",
            type: "full-time",
            category: "research",
            salary: "Rs. 130,000 - Rs. 170,000",
            logo: "LT",
            description: "Conduct scientific research and experiments. Publish findings and collaborate with academic partners.",
            tags: ["Research", "Analysis", "Publication", "Lab Work"],
            posted: "Today",
            remote: false
        },
        {
            id: 2016,
            title: "Finance Manager",
            company: "Capital Finance",
            location: "Lahore, Pakistan",
            type: "full-time",
            category: "finance",
            salary: "Rs. 150,000 - Rs. 200,000",
            logo: "CF",
            description: "Manage financial planning, reporting, and analysis. Oversee budgeting and compliance.",
            tags: ["Finance", "Budgeting", "Reporting", "Compliance"],
            posted: "Today",
            remote: false
        },
        {
            id: 2017,
            title: "Event Coordinator",
            company: "EventPro",
            location: "Karachi, Pakistan",
            type: "full-time",
            category: "event-planning",
            salary: "Rs. 100,000 - Rs. 140,000",
            logo: "EP",
            description: "Plan and manage corporate and social events. Coordinate logistics and vendor relations.",
            tags: ["Event Planning", "Logistics", "Vendor Management", "Coordination"],
            posted: "Today",
            remote: false
        },
        {
            id: 2018,
            title: "Administrative Officer",
            company: "AdminPro",
            location: "Islamabad, Pakistan",
            type: "full-time",
            category: "administrative",
            salary: "Rs. 90,000 - Rs. 120,000",
            logo: "AP",
            description: "Manage office administration and support daily operations. Maintain records and schedules.",
            tags: ["Administration", "Office Management", "Scheduling", "Records"],
            posted: "Today",
            remote: false
        },
        {
            id: 2019,
            title: "Foreign Language Translator",
            company: "LinguaWorld",
            location: "Lahore, Pakistan",
            type: "full-time",
            category: "foreign-languages",
            salary: "Rs. 110,000 - Rs. 150,000",
            logo: "LW",
            description: "Translate documents and interpret conversations for business and legal purposes.",
            tags: ["Translation", "Interpretation", "Languages", "Communication"],
            posted: "Today",
            remote: false
        },
        {
            id: 2020,
            title: "Client Relations Specialist",
            company: "ClientConnect",
            location: "Karachi, Pakistan",
            type: "full-time",
            category: "client-relations",
            salary: "Rs. 120,000 - Rs. 160,000",
            logo: "CC",
            description: "Build and maintain strong client relationships. Address client needs and ensure satisfaction.",
            tags: ["Client Relations", "Account Management", "Customer Service", "Communication"],
            posted: "Today",
            remote: false
        },
];

// Export for use in main.js
if (typeof module !== 'undefined' && module.exports) {
    module.exports = jobsData;
}
